### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

### Signin a user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "bombay@company.com",
    "password": "bombom"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/2

### Find a particular user with a given email
GET http://localhost:3000/auth?email=bom@aaaaa.com

### Delete a user with a given ID
DELETE http://localhost:3000/auth/13

### Update a user
PATCH  http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "bom@aaaaa.com",
    "password": "123"
}

### Set a color
GET http://localhost:3000/auth/colors/blue

### Get a color
GET http://localhost:3000/auth/colors


### Get whoami user
GET http://localhost:3000/auth/whoami


### Signout
POST  http://localhost:3000/auth/signout